In [1]:
import bs4
import urllib

In [2]:
url  = "https://manipalglobal.com"
html = urllib.request.urlopen(url)
bs_obj = bs4.BeautifulSoup(html.read(),'lxml')

In [3]:
bs_obj.html.head.title

In [42]:
bs_obj.html.body.img

In [43]:
bs_obj.html.body.a

<a class="first-top-item gnu-logo" href="/mage.html">
<img alt="MAGE" class="lazyload" data-src="/content/dam/manipal/mage/images/logos/logo.png" src=""/>
</a>

In [53]:
imgs = bs_obj.html.find_all('img')
len(imgs)

12

In [57]:
imgs[0].get('data-src')

'/content/dam/manipal/mage/images/logos/logo.png'

In [65]:
for img in imgs:
    print(img.get('data-src'))

/content/dam/manipal/mage/images/logos/logo.png
None
None
/content/dam/manipal/mage/images/logos/l&T.jpg
/content/dam/manipal/mage/images/logos/del.jpg
/content/dam/manipal/mage/images/logos/vir.jpg
/content/dam/manipal/mage/images/logos/viston.jpg
/content/dam/manipal/mage/images/logos/emc.jpg
/content/dam/manipal/mage/images/logos/infosys.png
/content/dam/manipal/mage/images/galleryImage/tma-pi.JPG.transform/140x93/image.jpg
/content/dam/manipal/mage/images/logos/mono-logo-footer.png.transform/295x78/image.png
None

In [68]:
hyper_link=bs_obj.find_all('a')
for hy in hyper_link:
    print(hy.get('href'))

/mage.html
/mage/news-events/news-room.html
/mage/careers.html
/mage/contact-us.html
/content.html
/content.html
/content.html
#request4info
/mage/news-events/news-room.html
/mage/careers.html
/mage/contact-us.html
http://www.manipalprolearn.com/programs/big-data-analytics-using-hadoop-blended
http://www.manipalprolearn.com/programs/cloud-computing-ms-azure-online
http://www.manipalprolearn.com/programs/android-app-development-0
http://www.manipalprolearn.com/programs/itil-foundation-online
http://www.manipalprolearn.com/programs/advanced-ms-excel
http://www.manipalprolearn.com/programs//?tid=7
http://www.manipalprolearn.com/programs/cima-advanced-diploma-management-accounting
http://www.manipalprolearn.com/programs/management-information-systems
http://www.manipalprolearn.com/programs/management-accounting
http://www.manipalprolearn.com/programs/financial-accounting
http://www.manipalprolearn.com/programs?tid=8
http://www.manipalprolearn.com/programs/digital-marketing-google
http://www.manipalprolearn.com/programs/mobile-marketing
http://www.manipalprolearn.com/programs/project-management-blended-0
http://www.manipalprolearn.com/programs/supply-chain-management
http://www.manipalprolearn.com/programs/ms-project
http://www.manipalprolearn.com/programs?tid=9
http://www.manipalprolearn.com/programs/comprehensive-developer-program-cstream
http://www.manipalprolearn.com/programs/c-developer-job-prep-stream
http://www.manipalprolearn.com/programs/comprehensive-developer-program-java-stream
http://www.manipalprolearn.com/programs?tid=27
#
#
None
None
None
None
None
None
/mage/news-events/news-room/walking-down-the-memory-lane.html
/mage/news-events/news-room/walking-down-the-memory-lane.html
/mage/news-events/news-room/golden-peacock-awards.html
/mage/news-events/news-room/golden-peacock-awards.html
/mage/news-events/news-room/ho-can-distance-learning-leverage.html
/mage/news-events/news-room/ho-can-distance-learning-leverage.html
/mage/news-events/news-room.html
/mage/news-events/news-room.html
/mage/news-events/events/lpi-learning-awards-2018-in-london.html
/mage/news-events/events/lpi-learning-awards-2018-in-london.html
/mage/news-events/events/nxtgen-leadership-summit.html
/mage/news-events/events/nxtgen-leadership-summit.html
/mage/news-events/events.html
/mage/news-events/events.html
/mage/contact-us.html
/mage/careers.html
/mage/news-events/news-room.html
#
/mage/manipal-edge.html
/mage/manipal-edge/innovative-solutions.html
/mage/manipal-edge/built-to-scale.html
/mage/manipal-edge/domain-competency.html
/mage/manipal-edge/product-customisation.html
/mage/manipal-edge/technology-enabled-solutions.html
/mage/manipal-edge/diverse-delivery-methods.html
/mage/manipal-prolearn.html
/mage/enterprise.html
/mage/enterprise/learning-solutions.html
/mage/enterprise/strategic-initiatives.html
/mage/enterprise/resource-centre.html
/mage/enterprise/platforms.html
/mage/enterprise/nxtgen-leadership.html
/mage/services.html
/mage/services/academic-services.html
/mage/services/marketing-and-enrolment.html
/mage/services/operations-and-management.html
/mage/services/student-services.html
/mage/our-institutions.html
/mage/our-institutions/aua0.html
/mage/our-institutions/gnu-malaysia.html
/mage/our-institutions/icici-mab.html
/mage/our-institutions/manipal-academy-of-banking.html
/mage/our-institutions/mcoms-nepal.html
/mage/our-institutions/miu-malaysia.html
/mage/our-institutions/mu-dubai.html
/mage/our-institutions/mmmc-malaysia.html
/mage/our-institutions/other-group-institutions.html
/mage/about-us.html
/mage/about-us/group-entities.html
/mage/about-us/our-story-mage.html
/mage/about-us/vision-and-values-mage.html
/mage/about-us/chairman-emeritus.html
/mage/about-us/leadership.html
/mage/about-us/beyond-business-mage.html
/mage/about-us/our-people.html
/mage/lp.html
/mage/lp/fast-career-program.html
/mage/lp/fclp.html
/mage/lp/IT-recruitment.html
/mage/lp/nxtgen-2016.html
/mage/lp/thank-you-nxt-gen.html
/mage/lp/learning-solutions.html
/mage/lp/digital-marketing-program.html
/mage/lp/registerforwebinar.html
/mage/lp/advanced-business-analytics.html
/mage/lp/advanced-ms-excel.html
/mage/lp/hdfc-life1.html
/mage/lp/rbl-bank.html
/mage/lp/cii-award.html
/mage/lp/employability-ecosystem.html
/mage/lp/thankyou-employablity-ecosystem.html
/mage/lp/thankyou-for-registering.html
/mage/lp/nxtgen-whitepaper-launch.html
/mage/lp/nxtgen-industry-whitepaper.html
/mage/lp/thank-you-nxtgen.html
/mage/whistle-blower-policy.html
/mage.html
/mage/contact-us.html
/mage/miscellaneous/privacy-policy.html
/mage/whistle-blower-policy.html
/mage/miscellaneous/terms-of-use.html
/mage/miscellaneous/disclaimer.html

In [70]:
import pandas as pd

In [71]:
url = 'https://en.wikipedia.org/wiki/Demographics_of_India'
tables =pd.read_html(url)

In [72]:
tables[0]

,0,1
0,Demographics of India,NaN
1,Map showing the population density of each dis...,NaN
2,Population,"1,324,171,354 (2016 est.)[1]"
3,Density,382 people per.sq.km (2011 est.)
4,Growth rate,1.19% (2016) (96th)
5,Birth rate,"19.3 births/1,000 population (2016 est.)"
6,Death rate,"7.3 deaths/1,000 population (2016 est.)"
7,Life expectancy,68.89 years (2009 est.)
8,• male,67.46 years (2009 est.)
9,• female,72.61 years (2009 est.)
10,Fertility rate,2.2 children born/woman (2016 est.)[2]
11,Infant mortality rate,"41 deaths/1,000 live births (2016 est.)[3]"
12,Age structure,NaN
13,0–14 years,"28.6% (male 190,075,426/female 172,799,553)[2]"
14,15–64 years,"63.6% (male 381,446,079/female 359,802,209) (2..."
15,65 and over,"5.3% (male 29,364,920/female 32,591,030) (2009..."
16,Sex ratio,NaN
17,At birth,1.10 male(s)/female (2013 est.)
18,Under 15,1.10 male(s)/female (2009 est.)
19,15–64 years,1.06 male(s)/female (2009 est.)
20,65 and over,0.90 male(s)/female (2009 est.)
21,Nationality,NaN
22,Major ethnic,See Ethnic Groups of India
23,Language,NaN
24,Official,See Languages of India

In [73]:
tables[1]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Year,Maddison (2001)[14],Clark (1967)[15][16][17],Biraben (1979)[16][18][19],Durand (1974)[20][16],McEvedy (1978)[21][16],Aggregate average,Period,Average % growth / century,NaN,NaN,NaN,NaN,NaN,NaN
1,Population,% growth / century,Population,% growth / century,Population,% growth / century,Population,% growth / century,Population,% growth / century,Population,% growth / century,NaN,NaN,NaN
2,"10,000 BC",—,—,—,—,—,—,—,—,100000,—,100000,—,Stone Age,3.9
3,4000 BC,—,—,—,—,—,—,—,—,1000000,3.9,1000000,3.9,NaN,NaN
4,2000 BC,—,—,—,—,—,—,—,—,6000000,9.4,6000000,9.4,Bronze Age,9.4
5,500 BC,—,—,—,—,—,—,—,—,25000000,10,25000000,10,Iron Age,10.2
6,400 BC,—,—,—,—,30000000,—,—,—,26600000,6.3,28300000,13.2,NaN,NaN
7,200 BC,—,—,—,—,55000000,35.4,—,—,30000000,6.3,42500000,22.5,Maurya era,22.5
8,1 AD,75000000,—,70000000,—,46000000,–9.3,75000000,—,34000000,6.5,60000000,18.8,Classical era,5.3
9,200,75000000,0,72500000,1.7,45000000,–1.1,75000000,0,39000000,7.1,61300000,1.1,NaN,NaN
10,400,75000000,0,75000000,1.7,32000000,–18.6,75000000,0,45000000,7.4,60400000,–0.7,NaN,NaN
11,500,75000000,0,75000000,0,33000000,3.1,75000000,0,48000000,6.5,61200000,1.3,NaN,NaN
12,600,75000000,0,75000000,0,37000000,12.1,75000000,0,51000000,6.5,62600000,2.3,Early medieval era,1.9
13,700,75000000,0,75000000,0,50000000,35.1,75000000,0,56500000,10.3,66300000,5.9,NaN,NaN
14,800,75000000,0,75000000,0,43000000,–16.3,75000000,0,62000000,10.3,66000000,–0.5,NaN,NaN
15,900,75000000,0,72500000,–3.5,38000000,–13.2,75000000,0,69500000,11.4,66000000,0,NaN,NaN
16,1000,75000000,0,70000000,–3.5,40000000,5.3,75000000,0,77000000,11.4,67400000,2.1,NaN,NaN
17,1100,81000000,8,72500000,3.5,51000000,27.5,81300000,8.4,80000000,3.9,73200000,8.6,Late medieval era,8.1
18,1200,87500000,8,75000000,3.5,65100000,27.5,88200000,8.4,83000000,3.8,79800000,9,NaN,NaN
19,1300,94500000,8,75000000,0,83000000,27.5,95700000,8.4,88000000,6,87200000,9.3,NaN,NaN
20,1400,102000000,8,77000000,3.3,88800000,7,103700000,8.4,94000000,6.8,92900000,7,NaN,NaN
21,1500,110000000,8,79000000,3.3,95000000,7,112500000,8.4,100000000,6.4,99300000,7,NaN,NaN
22,1600,135000000,22.8,100000000,26.6,145000000,52.6,135800000,20.7,130000000,30,129200000,30.1,Mughal era,31.9
23,1650,150000000,22.2,150000000,125,160000000,20.7,149100000,20.7,145000000,24.4,150800000,36.2,NaN,NaN
24,1700,165000000,22.2,200000000,77.8,175000000,20.7,163900000,20.7,160000000,21.8,172800000,31.3,NaN,NaN
25,1750,182100000,21.8,200000000,0,182700000,9,180000000,20.7,170000000,12.9,183000000,12.1,Colonial era,12.2
26,1800,200900000,21.8,190000000,–10.8,190700000,9,—,—,185000000,18.4,190400000,8,NaN,NaN
27,1820,209000000,21.8,190000000,0,194000000,9,—,—,200000000,47.7,198300000,22,NaN,NaN

In [75]:
!pip install tweepy
import tweepy

Collecting tweepy
  Downloading https://files.pythonhosted.org/packages/05/f1/2e8c7b202dd04117a378ac0c55cc7dafa80280ebd7f692f1fa8f27fd6288/tweepy-3.6.0-py2.py3-none-any.whl
Collecting requests-oauthlib>=0.7.0 (from tweepy)
  Downloading https://files.pythonhosted.org/packages/94/e7/c250d122992e1561690d9c0f7856dadb79d61fd4bdd0e598087dce607f6c/requests_oauthlib-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in c:\users\name\anaconda3\lib\site-packages (from tweepy)
Requirement already satisfied: requests>=2.11.1 in c:\users\name\anaconda3\lib\site-packages (from tweepy)
Requirement already satisfied: PySocks>=1.5.7 in c:\users\name\anaconda3\lib\site-packages (from tweepy)
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.7.0->tweepy)
  Downloading https://files.pythonhosted.org/packages/e6/d1/ddd9cfea3e736399b97ded5c2dd62d1322adef4a72d816f1ed1049d6a179/oauthlib-2.1.0-py2.py3-none-any.whl (121kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy)
Installing collected packages: oauthlib, requests-oauthlib, tweepy
Successfully installed oauthlib-2.1.0 requests-oauthlib-1.0.0 tweepy-3.6.0

You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [1]:
import tweepy

In [2]:
consumer_key = "TufHzi954jfLE7O8YHtK2iFx9"
consumer_secret = "x5QhSUCQfV4QYQd5UfRyVeP8tJSMknEJs07WdOXhTGGh3KdfXx"
access_token = "887731387322650624-UTsVRJN1tnwHuGD8TcZNnKuo0OAf9jj"
access_token_secret = "YWY6AWChWiz6OUaV6ePDyJKcVna03P1vP2nYVautvfIEZ"
auth =tweepy.OAuthHandler(consumer_key,consumer_secret)
auth.set_access_token(access_token,access_token_secret)

#accesing twitter api
api =tweepy.API(auth,wait_on_rate_limit =True)
api

In [15]:
kiki_challenge = api.search('#bobbalalokesh')

In [17]:
kiki_challenge[0]

Status(_api=<tweepy.api.API object at 0x0000022D1E7A9BA8>, _json={'created_at': 'Fri Mar 01 04:36:40 +0000 2019', 'id': 1101340452546985985, 'id_str': '1101340452546985985', 'text': '#bobbalalokesh fdfsfdsfs', 'truncated': False, 'entities': {'hashtags': [{'text': 'bobbalalokesh', 'indices': [0, 14]}], 'symbols': [], 'user_mentions': [], 'urls': []}, 'metadata': {'result_type': 'recent', 'iso_language_code': 'tr'}, 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 795698154, 'id_str': '795698154', 'name': 'ravindra', 'screen_name': 'ravindrabvr', 'location': '', 'description': 'Indian.I care for our motherland.', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 0, 'friends_count': 287, 'listed_count': 0, 'created_at': 'Sat Sep 01 09:20:54 +0000 2012', 'favourites_count': 73, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 134, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', 'profile_link_color': '3B94D9', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'tr'}, created_at=datetime.datetime(2019, 3, 1, 4, 36, 40), id=1101340452546985985, id_str='1101340452546985985', text='#bobbalalokesh fdfsfdsfs', truncated=False, entities={'hashtags': [{'text': 'bobbalalokesh', 'indices': [0, 14]}], 'symbols': [], 'user_mentions': [], 'urls': []}, metadata={'result_type': 'recent', 'iso_language_code': 'tr'}, source='Twitter Web Client', source_url='http://twitter.com', in_reply_to_status_id=None, in_reply_to_status_id_str=None, in_reply_to_user_id=None, in_reply_to_user_id_str=None, in_reply_to_screen_name=None, author=User(_api=<tweepy.api.API object at 0x0000022D1E7A9BA8>, _json={'id': 795698154, 'id_str': '795698154', 'name': 'ravindra', 'screen_name': 'ravindrabvr', 'location': '', 'description': 'Indian.I care for our motherland.', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 0, 'friends_count': 287, 'listed_count': 0, 'created_at': 'Sat Sep 01 09:20:54 +0000 2012', 'favourites_count': 73, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 134, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', 'profile_link_color': '3B94D9', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, id=795698154, id_str='795698154', name='ravindra', screen_name='ravindrabvr', location='', description='Indian.I care for our motherland.', url=None, entities={'description': {'urls': []}}, protected=False, followers_count=0, friends_count=287, listed_count=0, created_at=datetime.datetime(2012, 9, 1, 9, 20, 54), favourites_count=73, utc_offset=None, time_zone=None, geo_enabled=False, verified=False, statuses_count=134, lang='en', contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='000000', profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', profile_link_color='3B94D9', profile_sidebar_border_color='000000', profile_sidebar_fill_color='000000', profile_text_color='000000', profile_use_background_image=False, has_extended_profile=True, default_profile=False, default_profile_image=False, following=False, follow_request_sent=False, notifications=False, translator_type='none'), user=User(_api=<tweepy.api.API object at 0x0000022D1E7A9BA8>, _json={'id': 795698154, 'id_str': '795698154', 'name': 'ravindra', 'screen_name': 'ravindrabvr', 'location': '', 'description': 'Indian.I care for our motherland.', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 0, 'friends_count': 287, 'listed_count': 0, 'created_at': 'Sat Sep 01 09:20:54 +0000 2012', 'favourites_count': 73, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 134, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', 'profile_link_color': '3B94D9', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, id=795698154, id_str='795698154', name='ravindra', screen_name='ravindrabvr', location='', description='Indian.I care for our motherland.', url=None, entities={'description': {'urls': []}}, protected=False, followers_count=0, friends_count=287, listed_count=0, created_at=datetime.datetime(2012, 9, 1, 9, 20, 54), favourites_count=73, utc_offset=None, time_zone=None, geo_enabled=False, verified=False, statuses_count=134, lang='en', contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='000000', profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1040980673731944455/V3gCK3zG_normal.jpg', profile_link_color='3B94D9', profile_sidebar_border_color='000000', profile_sidebar_fill_color='000000', profile_text_color='000000', profile_use_background_image=False, has_extended_profile=True, default_profile=False, default_profile_image=False, following=False, follow_request_sent=False, notifications=False, translator_type='none'), geo=None, coordinates=None, place=None, contributors=None, is_quote_status=False, retweet_count=0, favorite_count=0, favorited=False, retweeted=False, lang='tr')

In [20]:
for kiki in kiki_challenge:
    print(kiki.author.name,kiki.author.favourites_count,kiki.text)
    print('---------')

ravindra 73 #bobbalalokesh fdfsfdsfs
---------

In [97]:
!pip install mechanicalsoup

Collecting mechanicalsoup
  Downloading https://files.pythonhosted.org/packages/e7/e0/632f58365452f491eb587e6c75907f5f78a60961242e38fb4777d60dba5d/MechanicalSoup-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.0 in c:\users\name\anaconda3\lib\site-packages (from mechanicalsoup)
Requirement already satisfied: six>=1.4 in c:\users\name\anaconda3\lib\site-packages (from mechanicalsoup)
Requirement already satisfied: beautifulsoup4 in c:\users\name\anaconda3\lib\site-packages (from mechanicalsoup)
Requirement already satisfied: lxml in c:\users\name\anaconda3\lib\site-packages (from mechanicalsoup)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.0->mechanicalsoup)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.0->mechanicalsoup)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.0->mechanicalsoup)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\name\anaconda3\lib\site-packages (from requests>=2.0->mechanicalsoup)
Installing collected packages: mechanicalsoup
Successfully installed mechanicalsoup-0.10.0

You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [111]:
import mechanicalsoup
browser = mechanicalsoup.StatefulBrowser()
browser.open('https://goo.gl/forms/UMkVQlBgOIl3IYzG3')

In [106]:
page = browser.get_current_page()
browser.select_form('form')
browser['entry.5670709'] = 'ravindra'
browser.submit_selected()

In [112]:
page = browser.get_current_page()
browser.select_form('form')
browser['entry.846808492'] = 'yes'
browser.submit_selected()